markdown: kramdown
title: Ebon
author: Ebon
author_email: ebonindia@gmail.com
description: Outsourcing is awesome, save your time
url: http://ebonnow.com/
permalink: pretty
plugins:
  - jekyll-sitemap
